apiVersion: v1
baseDomain: lab.local
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 0 # Must be set to 0 for User Provisioned Installation as worker nodes will be manually deployed.
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: ocp # Cluster name
networking:
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
    - 172.30.0.0/16
platform:
  vsphere:
    vcenter: 192.168.77.66
    username: administrator
    password: supersecretpassword
    datacenter: Datacenter
    defaultDatastore: DataStore
fips: false
pullSecret: ''
sshKey: ""
